name: Deploy to DigitalOcean K8s

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
                description: "Environment to deploy to (staging/production)"
            service_name:
                required: true
                type: string
                description: "Service name (frontend/backend)"
            image_tag:
                required: true
                type: string
                description: "Docker image tag to deploy"
            ecr_repository:
                required: true
                type: string
                description: "ECR repository name"
        secrets:
            DIGITALOCEAN_ACCESS_TOKEN:
                required: true
            DO_CLUSTER_ID:
                required: true
            ECR_REGISTRY:
                required: true
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Configure kubectl for DigitalOcean
              run: |
                  doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_ID }}

            - name: Configure AWS credentials for ECR
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Update Kubernetes deployment
              env:
                  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
                  ECR_REPOSITORY: ${{ inputs.ecr_repository }}
                  IMAGE_TAG: ${{ inputs.image_tag }}
                  SERVICE_NAME: ${{ inputs.service_name }}
                  ENVIRONMENT: ${{ inputs.environment }}
              run: |
                  # Set image for deployment
                  IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

                  echo "🔄 Updating deployment $SERVICE_NAME with image: $IMAGE_URI"

                  # Check current deployment status before update
                  echo "📋 Current deployment status:"
                  kubectl get deployment $SERVICE_NAME -n $ENVIRONMENT || echo "Deployment not found"
                  kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME || echo "No pods found"

                  # Update deployment
                  kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$IMAGE_URI -n $ENVIRONMENT

                  # Wait for rollout to complete with longer timeout
                  echo "⏳ Waiting for rollout to complete..."
                  kubectl rollout status deployment/$SERVICE_NAME -n $ENVIRONMENT --timeout=600s || {
                    echo "❌ Rollout failed or timed out. Checking status..."
                    
                    # Debug information
                    echo "📋 Deployment describe:"
                    kubectl describe deployment $SERVICE_NAME -n $ENVIRONMENT
                    
                    echo "📋 Pod status:"
                    kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME -o wide
                    
                    echo "📋 Events:"
                    kubectl get events -n $ENVIRONMENT --sort-by=.metadata.creationTimestamp | tail -20
                    
                    # Try to get logs from failing pods
                    echo "📋 Pod logs:"
                    kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME --field-selector=status.phase!=Running -o name | head -3 | xargs -I {} kubectl logs {} -n $ENVIRONMENT --tail=50 || true
                    
                    exit 1
                  }

                  # Verify deployment
                  kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME

                  echo "✅ Successfully deployed $SERVICE_NAME:$IMAGE_TAG to $ENVIRONMENT"

            - name: Run deployment verification
              env:
                  SERVICE_NAME: ${{ inputs.service_name }}
                  ENVIRONMENT: ${{ inputs.environment }}
              run: |
                  echo "🔍 Running final verification..."

                  # Check if deployment is ready with longer timeout
                  kubectl wait --for=condition=available --timeout=600s deployment/$SERVICE_NAME -n $ENVIRONMENT || {
                    echo "❌ Deployment not ready. Final status check:"
                    kubectl get deployment $SERVICE_NAME -n $ENVIRONMENT
                    kubectl describe deployment $SERVICE_NAME -n $ENVIRONMENT
                    exit 1
                  }

                  # Get service info
                  echo "📋 Final Deployment Status:"
                  kubectl get deployment $SERVICE_NAME -n $ENVIRONMENT

                  echo "📋 Final Pod Status:"
                  kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME -o wide

                  # Check if all pods are running
                  RUNNING_PODS=$(kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME --field-selector=status.phase=Running --no-headers | wc -l)
                  TOTAL_PODS=$(kubectl get pods -n $ENVIRONMENT -l app=$SERVICE_NAME --no-headers | wc -l)

                  echo "📊 Pods Summary: $RUNNING_PODS/$TOTAL_PODS running"

                  if [ "$RUNNING_PODS" -eq "$TOTAL_PODS" ]; then
                    echo "✅ All pods are running successfully!"
                  else
                    echo "⚠️ Some pods are not running. Check logs above."
                  fi
